Ajv serializer
fastify/ajv-compiler pull request #45
Opened 2021-12-06 11:58 UTC by Eomm

Opening this draft to get feedback.
Right now this feature works, it needs more testing (CI fails due to the coverage).

The notable code is on the `index` and `serializer-compiler` files, the `validator` is just a copy-paste

AJV-JTD can be used to serialize the JSON payloads: https://ajv.js.org/guide/getting-started.html#parsing-and-serializing-json

I'm not sure if it is good to include this feature in this package, or we should create a new package that:

- support `fast-json-stringify` by default
- let the user opt-in to `ajv-JTD` feature

What do you think?

Closes https://github.com/fastify/fastify/issues/3441

2021-12-09 14:53 UTC, jsumners commented
I don't see any issue with this.

2021-12-13 06:32 UTC, dalisoft commented
@Eomm Any performance comparison would be helpful

2022-10-18 12:46 UTC, mcollina requested changes
I would call the option jtdSerializer:

2022-10-23 09:31 UTC, Eomm commented
Must add small benchmarks

2022-10-25 07:25 UTC, mcollina approved these changes
lgtm

2022-10-25 11:46 UTC, jsumners approved these changes
Looks good to me.

2022-10-31 08:19 UTC, merged