Ajv 8
fastify/ajv-compiler pull request #7
Opened 2021-04-22 21:41 UTC by Eomm

This is just a draft PR for ajv8 support - it is a semver major

The interface exposed to fastify is unchanged, but under the hood ajv8 is running 👍🏽 

TODO:

- [ ] optimize default configuration
- [ ] add tests for most used ajv plugins
- [ ] update docs

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2021-05-26 10:03 UTC, wa-Nadoo commented on package.json
>      "ajv-merge-patch": "^4.1.0",
Seems like 'ajv-merge-patch' is unused

2021-06-09 06:48 UTC, mcollina commented
I'm a bit lost on the standalone usage to end users.
The main "client" of this is Fastify itself for its configs.

2021-08-09 19:21 UTC, mcollina approved these changes
lgtm

2021-08-10 07:13 UTC, zekth requested changes
Minor comment otherwise LGTM.

Thinking out loud: the write/read mode could be exported as a feature of the `fastify-cli` like some test runners have for snapshots. We would be have to do `fastify build --write-schemas` or something. That would be really convinient.

2021-08-10 07:13 UTC, zekth commented on standalone.js
> +    /*************/
```suggestion
    
```

2021-08-10 07:13 UTC, zekth commented on standalone.js
> +  /*************/
```suggestion

```

2021-08-10 07:22 UTC, Eomm commented
> Thinking out loud: the write/read mode could be exported as a feature of the fastify-cli 

This would be good indeed, but the user needs to change the code to give us the control of the `fastify` instance in some way

2021-08-10 07:24 UTC, zekth commented
> > Thinking out loud: the write/read mode could be exported as a feature of the fastify-cli
> 
> This would be good indeed, but the user needs to change the code to give us the control of the `fastify` instance in some way

Maybe that's a feature we could put in the scope of v4. What's your thought on it @mcollina ?

2021-08-10 07:25 UTC, zekth approved these changes

2021-08-16 14:13 UTC, mcollina commented
> > > Thinking out loud: the write/read mode could be exported as a feature of the fastify-cli
> 
> > 
> 
> > This would be good indeed, but the user needs to change the code to give us the control of the `fastify` instance in some way
> 
> 
> 
> Maybe that's a feature we could put in the scope of v4. What's your thought on it @mcollina ?

let's go for it! Could you open a fresh issue on fastify-cli?^

2021-08-16 17:07 UTC, Eomm commented
I have added tests/examples for

- [x] ajv-formats
- [x] ajv-errors
- [x] ajv-i18n

I think we are ready to publish the v2 of this module and add some docs for Fastify v3

2021-08-17 12:39 UTC, zekth approved these changes

2021-08-17 12:42 UTC, jsumners approved these changes
Looks good to me.

2021-08-17 13:04 UTC, merged